### ISSUE TITLE
Tooltip for "Mark as Incomplete" Button on Graded Assignments

### ISSUE THREAD

**Issue by TheVanadium** [jtcheng26/canvas-task-extension#120]
<img src="https://github.com/jtcheng26/canvas-task-extension/assets/53013571/f19f56f9-cb06-48a3-aade-ef4d03ffa192" width="200" height="480"> <br>
The button symbols don't indicate very well what their function is supposed to do (they seem more like a "reload" button), so a tooltip may help.

**Comment by TheVanadium** [comment]
I'd work on this myself, but I can't figure out how to run it on Firefox; the zipped firefox build folder causes Firefox to complain about the manifest.json file being invalid.

**Comment by jtcheng26** [comment]
Sounds good, just submit a PR when you're done. You're free to add this to other types of buttons as well. Also, if you have any better ideas for a button icon, that would be great to know. Thanks!
