### ISSUE TITLE
Gradescope Integration

### ISSUE THREAD

**Issue by jtcheng26** [jtcheng26/canvas-task-extension#129]
Initial plan:
- There will also be the option to automatically sync a class's assignments (opt-in)
  - It will sync every time the user opens gradescope (i.e. to submit an assignment), I think this is the only way to do it since no official API is provided
- There will be a global option to disable this feature entirely
- Gradescope synced assignments will be stored in local storage
  - ~~Identified by (course, index on page)~~
  - ~~Linking to the correct course will be a challenge, I'm thinking just compare names and allow the user to edit for the ones that don't get matched/are matched incorrectly~~
    - Just let the user pick the class (1-3 extra clicks), but suggest a recommended based on name matching
- Assignment info will just be scraped (name, link, status, due date)
  - When adding to Canvas, compare it with existing assignments and only add if there is no assignment with the same due date, course, and similar name
- Nothing will be fetched while the user is taking a quiz (the submit button is present)
  - Not sure if this is necessary, just don't want it to interfere with anything important
- _Maybe a "Tasks for Gradescope" sidebar on the Gradescope dashboard_

~~I think this update needs to go out after editing custom tasks.~~
Users will be able to delete the tasks just like custom tasks, editing isn't a problem since task name, course, and due date should be accurate.

**Comment by ed789d0** [comment]
> Identified by (course, index on page)
Could you use the assignment ID number in each assignment's link instead of the index on the page? I don't know if it's important to store assignments with no links (e.g. ones that are locked or weren't submitted)

**Comment by jtcheng26** [comment]
I'm thinking if we just scrape all the assignments for the course at once, we don't really need to keep track of individual assignments, just update the whole list in storage when the script runs. I'd also like having the ones without links (but with a due date) to still show up, it'll just link to the course's gradescope page instead of the submission page.

**Comment by ed789d0** [comment]
Just tried it in Edge, and I like the implementation (though maybe a warning for "You haven't opened Gradescope in 3 days. Click here to open it in the background and sync" or something like that would be helpful). I don't think I had any issues at all.

**Comment by ed789d0** [comment]
Actually, one issue: a lot of people use Gradescope in the respective Canvas course's "Gradescope" tab. The extension doesn't seem to be able to access this iframe at all (I don't see the "Synced with Tasks for Canvas" button in the iframe).

**Comment by jtcheng26** [comment]
> Actually, one issue: a lot of people use Gradescope in the respective Canvas course's "Gradescope" tab. The extension doesn't seem to be able to access this iframe at all (I don't see the "Synced with Tasks for Canvas" button in the iframe).

There's a manifest key to enable the extension to run in iframes which should resolve this, I just need to check if it creates any new permissions warnings when updated
