### ISSUE TITLE
Grades aren't rounded

### ISSUE THREAD

**Issue by ed789d0** [jtcheng26/canvas-task-extension#132]
Really a nitpick more than anything, but the sidebar shows all the decimal places that Canvas has for a certain grade:
![image](https://github.com/jtcheng26/canvas-task-extension/assets/26331505/f4f4cfc8-3ed1-46ae-bf73-f424e62c2888)
It might be good to round the decimal.

**Comment by jtcheng26** [comment]
I noticed this too, I'll probably fix it in the next update
