### ISSUE TITLE
Too many Gradescope assignments for the storage?

### ISSUE THREAD

**Issue by ed789d0** [jtcheng26/canvas-task-extension#138]
I have a Gradescope class with a _lot_ of past assignments, and the past and current assignments for the class don't show up in Tasks for Canvas. I think I found why:

DevTools console message:
![image](https://github.com/jtcheng26/canvas-task-extension/assets/26331505/cd75c9ad-3ba1-4b53-9fd9-a9bddc8deffe)

Browser console message:
![image](https://github.com/jtcheng26/canvas-task-extension/assets/26331505/d320afe5-e56e-400b-9452-651d19df3701)

The two above screenshots are from Firefox, but here's the same issue in Edge DevTools:
![image](https://github.com/jtcheng26/canvas-task-extension/assets/26331505/b74c1043-9371-49e5-a357-4aeab0e99548)

**Comment by jtcheng26** [comment]
chrome.storage.sync only has an 8kb quota per storage item apparently (100kb total), so the solution is probably to just move Gradescope things to local storage, which has 100x higher limits
