### ISSUE TITLE
Publish on AMO

### ISSUE THREAD

**Issue by ed789d0** [jtcheng26/canvas-task-extension#23]
Unlike Chrome, Firefox will only install extensions that are in the store (addons.mozilla.org or AMO) or uploaded to Mozilla to be signed. Is there a plan to get this extension in the store? (It's free)

**Comment by jtcheng26** [comment]
The extension is submitted to the addons store already and is awaiting review. When it passes, it'll be at https://addons.mozilla.org/en-US/firefox/addon/tasks-for-canvas/
