### ISSUE TITLE
Custom tasks not saving properly

### ISSUE THREAD

**Issue by jtcheng26** [jtcheng26/canvas-task-extension#49]
Some users are reporting issues with custom tasks:

- not saving after reload
- selected course being unassigned after reload

Need help reproducing the issue. See [Task Form](https://github.com/jtcheng26/canvas-task-extension/blob/main/src/pages/Content/modules/components/task-form/TaskForm.tsx) and [Create Custom Task](https://github.com/jtcheng26/canvas-task-extension/blob/main/src/pages/Content/modules/utils/createCustomTask.ts).

**Comment by hendersonyang** [comment]
Getting a 400 error with message 
`{"errors":{"plannable_id":[{"attribute":"plannable_id","type":"taken","message":"taken"}]}}`
when trying to complete a task and it sends a request to {myschool}.instructure.com/api/v1/planner/overrides

**Comment by jtcheng26** [comment]
Did this happen right after creating a new task? Or with an assignment created by the teacher? 

There is also a known issue where marking a task complete for the first time, then immediately resetting it will leave it in the completed state after reload because of the error you mentioned.

**Comment by hendersonyang** [comment]
This happens after trying to complete a task. The custom tasks are stuck in unfinished, even when marking a task complete for the first time.

**Comment by jtcheng26** [comment]
Update: error could be that the csrf token cookie isn't set in some Canvas instances. This might be a different issue though, can you check if the _csrf_token cookie is set in your Canvas?

Inspect element -> Application -> Cookies -> {myschool}.instructure.com -> look for _csrf_token on the right side.

**Comment by hendersonyang** [comment]
The _csrf_token cookie is there. 

I created a task, and then immediately marked as complete, this is the exact request from "Copy as fetch":
```js
fetch("https://{myschool}.instructure.com/api/v1/planner/overrides", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "sec-gpc": "1",
    "x-csrf-token": "{randomstring}"
  },
  "referrer": "https://{myschool}.instructure.com/",
  "referrerPolicy": "no-referrer-when-downgrade",
  "body": "{\"plannable_type\":\"planner_note\",\"plannable_id\":179000000000004960,\"marked_complete\":true}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```
response: (status code 201)
```json
{"id":12195791,"plannable_type":"planner_note","plannable_id":179000000000004960,"user_id":179000000000037507,"workflow_state":"active","marked_complete":true,"deleted_at":null,"created_at":"2023-01-18T05:20:26Z","updated_at":"2023-01-18T05:20:26Z","dismissed":false,"assignment_id":null}
```

However the task still appears, and when marking as complete again. It gives 400 response:
```json
{"errors":{"plannable_id":[{"attribute":"plannable_id","type":"taken","message":"taken"}]}}
```

The only way I can get rid of the task is to delete it from the canvas student calendar.

I probably should have gave more detailed information earlier 😅

**Comment by jtcheng26** [comment]
Ohh I see, the problem is the extension stores plannable_id as a number and 179000000000004960 is too big 😄
Didn't realize this was possible, so I'll just switch everything over to strings. Thank you so much for sharing those details!
