### ISSUE TITLE
Better dark mode compatibility

### ISSUE THREAD

**Issue by jtcheng26** [jtcheng26/canvas-task-extension#77]
Work better with dark mode extensions, maybe detect if the background color is dark, then switch to dark styles

**Comment by ed789d0** [comment]
There are still some issues with Dark Reader + Firefox + this extension:
![image](https://github.com/jtcheng26/canvas-task-extension/assets/26331505/59f8d88f-dfe0-415e-9396-38ec8e85dbd9)

(also, not all of the course colors match up with the ones in the Canvas cards)
